# Generated by Django 4.2.4 on 2024-03-28 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_image_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlisted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
