# Generated by Django 4.2.4 on 2024-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_max_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='max_bid',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=6), max_digits=6),
        ),
    ]
