# Generated by Django 4.2.4 on 2024-03-30 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_price_listing_initial_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='wishlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
