# Generated by Django 4.2.4 on 2024-03-30 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
