# Generated by Django 4.2.4 on 2024-04-01 22:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 1, 22, 13, 58, 685886, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
